import subprocess
import numpy as np
import os

class StructureGenerator:
    def __init__(self, work_dir: str, spparks_exe: str = "spk_linux"):
        self.work_dir = work_dir
        self.exe = spparks_exe
        os.makedirs(work_dir, exist_ok=True)

    def generate_initial_microstructure(self, size: int, num_seeds: int, target_porosity: float) -> str:
        """
        Generates initial microstructure following the thesis recommendations.
        """

        # Phase 1: Create Input Script for Grain Growth
        growth_script_path = os.path.join(self.work_dir, "growth.in")
        dump_file = "dump_growth.txt"

        # Note: The syntax below is based on SPPARKS input script format
        growth_script = f"""
        seed 12345
        app_style potts
        dimension 3
        lattice sc/26n 1.0
        region box block 0 {size} 0 {size} 0 {size}
        create_box box
        create_sites box

        set site range 1 {size**3} value 0
        set site loop {num_seeds} unique value 1 {num_seeds}

        temperature 1.0
        stats 100

        run 100

        dump 1 all {dump_file}
        """

        with open(growth_script_path, "w") as f:
            f.write(growth_script)

        # Phase 2: Mock Execute SPPARKS
        # In real scenario: subprocess.run([self.exe, "-in", growth_script_path], ...)
        self._mock_spparks_execution(os.path.join(self.work_dir, dump_file), size, num_seeds)

        # Phase 3: Apply Porosity
        return self._apply_porosity(dump_file, target_porosity, size)

    def _mock_spparks_execution(self, dump_path: str, size: int, num_ids: int):
        # Mocking the output of SPPARKS dump
        # We create a random grid
        grid = np.random.randint(1, num_ids + 1, size=(size, size, size))
        # Write it in a way that _parse_dump might read, or just skip if we use in-memory in apply
        # For this prototype, I will just ensure the file exists if needed.
        pass

    def _apply_porosity(self, dump_file: str, porosity: float, size: int) -> str:
        # Mock reading
        data = np.random.randint(1, 20, size=(size, size, size))

        # Apply porosity
        total_sites = data.size
        num_pores = int(total_sites * porosity)

        indices = np.random.choice(total_sites, num_pores, replace=False)
        flat_data = data.flatten()
        flat_data[indices] = 0
        final_grid = flat_data.reshape((size, size, size))

        output_file = os.path.join(self.work_dir, "start_structure.txt")
        self._write_spparks_input_format(final_grid, output_file)

        return output_file

    def _parse_dump(self, filename, size):
        return np.zeros((size, size, size), dtype=int)

    def _write_spparks_input_format(self, grid, filename):
        flat = grid.flatten()
        with open(filename, "w") as f:
            f.write(f"# SPPARKS input file generated by NanoSinterWeb\n")
            f.write(f"{len(flat)} sites\n\n")
            f.write("Values\n\n")
            for i, val in enumerate(flat):
                f.write(f"{i+1} {val}\n")
